import SwiftUI
import Cocoa

// MARK: - Apple HIG Connected AI Assistants View (Universal Hybrid)
public struct DashboardWorkspacesView: View {
    @Binding var watchAntigravity: Bool
    @Binding var watchClaude: Bool
    @Binding var watchOpenCode: Bool
    @Binding var watchTerminal: Bool
    
    @ObservedObject var connectorManager = UniversalConnectorManager.shared
    
    // UI Local States
    @State private var recipeInput: String = ""
    @State private var recipeFeedbackMessage: String? = nil
    @State private var recipeFeedbackIsError: Bool = false
    @State private var promptCopied: Bool = false
    
    // Manual Watcher Form States
    @State private var manualName: String = ""
    @State private var manualPath: String = ""
    @State private var manualFormat: ConnectorFormat = .jsonl
    @State private var manualFeedbackMessage: String? = nil
    @State private var manualFeedbackIsError: Bool = false
    
    public init(
        watchAntigravity: Binding<Bool>,
        watchClaude: Binding<Bool>,
        watchOpenCode: Binding<Bool>,
        watchTerminal: Binding<Bool>
    ) {
        self._watchAntigravity = watchAntigravity
        self._watchClaude = watchClaude
        self._watchOpenCode = watchOpenCode
        self._watchTerminal = watchTerminal
    }
    
    public var body: some View {
        ScrollView(.vertical, showsIndicators: true) {
            VStack(alignment: .leading, spacing: 18) {
                // 1. Privacy Banner
                privacyCard
                
                // 2. Built-in Top AI Assistants
                builtinAssistantsSection
                
                // 3. Universal AI Connector (Prompt & Paste Recipe)
                universalPromptConnectorSection
                
                // 4. Active Custom Connectors (if any)
                if !connectorManager.customConnectors.isEmpty {
                    activeCustomConnectorsSection
                }
                
                // 5. Terminal & Shell Harnesses (Pipes & Sockets)
                terminalHarnessSection
                
                // 6. Manual Folder / File Watcher
                manualWatcherSection
            }
            .padding(.vertical, 10)
            .padding(.horizontal, 2)
        }
    }
    
    // MARK: - Privacy Banner
    private var privacyCard: some View {
        HStack(spacing: 12) {
            ZStack {
                RoundedRectangle(cornerRadius: 6, style: .continuous)
                    .fill(Color.green.opacity(0.15))
                    .frame(width: 28, height: 28)
                Image(systemName: "lock.shield.fill")
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundColor(.green)
            }
            
            VStack(alignment: .leading, spacing: 2) {
                Text("100% Private • Local File & Socket Listening")
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundColor(.primary)
                Text("Agent Speak only vocalizes text generated by your coding tools. It never uses, records, or monitors your microphone.")
                    .font(.system(size: 11))
                    .foregroundColor(.secondary)
            }
            Spacer()
        }
        .padding(12)
        .background(Color(nsColor: .controlBackgroundColor))
        .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
        )
    }
    
    // MARK: - Built-in Top Assistants
    private var builtinAssistantsSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("CONNECTED AI CODING ASSISTANTS")
                .font(.system(size: 11, weight: .semibold))
                .foregroundColor(.secondary)
                .tracking(0.5)
            
            VStack(spacing: 0) {
                // Antigravity
                workspaceRow(
                    icon: "circle.hexagongrid.circle.fill",
                    color: .purple,
                    title: "Antigravity Assistant",
                    subtitle: "Speaks conversational responses from Antigravity IDE and CLI",
                    isDetected: true,
                    isOn: $watchAntigravity
                )
                Divider().padding(.horizontal, 14)
                
                // Claude Code
                workspaceRow(
                    icon: "terminal.fill",
                    color: .orange,
                    title: "Claude Code CLI",
                    subtitle: "Speaks answers and explanations from Claude Code terminal sessions",
                    isDetected: checkPath("~/.claude/projects"),
                    isOn: $watchClaude
                )
                Divider().padding(.horizontal, 14)
                
                // OpenCode & OpenHands
                workspaceRow(
                    icon: "chevron.left.forwardslash.chevron.right",
                    color: .cyan,
                    title: "OpenCode & OpenHands",
                    subtitle: "Speaks activity logs and answers from supported developer agents",
                    isDetected: checkPath("~/.local/share/opencode"),
                    isOn: $watchOpenCode
                )
                Divider().padding(.horizontal, 14)
                
                // Presets from Manager (Cursor, Cline, Roo Code, Windsurf, Hermes, Aider)
                ForEach(connectorManager.presetConnectors) { preset in
                    presetConnectorRow(preset: preset)
                    Divider().padding(.horizontal, 14)
                }
                
                // Terminal & UNIX Socket
                workspaceRow(
                    icon: "apple.terminal.on.rectangle.fill",
                    color: .green,
                    title: "Terminal & UNIX Socket",
                    subtitle: "Accepts speech commands from custom shell scripts, pipes, and CLI",
                    isDetected: true,
                    isOn: $watchTerminal
                )
            }
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
        }
    }
    
    // MARK: - Universal AI Connector (Prompt & Paste Recipe)
    private var universalPromptConnectorSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Text("UNIVERSAL AI CONNECTOR")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundColor(.secondary)
                    .tracking(0.5)
                Spacer()
                Text("Connect Any Agent or Harness")
                    .font(.system(size: 11))
                    .foregroundColor(.blue)
            }
            
            VStack(alignment: .leading, spacing: 14) {
                HStack(alignment: .top, spacing: 12) {
                    ZStack {
                        RoundedRectangle(cornerRadius: 8, style: .continuous)
                            .fill(Color.blue.opacity(0.15))
                            .frame(width: 34, height: 34)
                        Image(systemName: "sparkles")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundColor(.blue)
                    }
                    
                    VStack(alignment: .leading, spacing: 3) {
                        Text("Connect Any New AI with a Single Prompt")
                            .font(.system(size: 13, weight: .semibold))
                            .foregroundColor(.primary)
                        Text("Copy our universal prompt, paste it to your AI tool (or ask your agent to configure another app), and paste the resulting JSON recipe below.")
                            .font(.system(size: 11))
                            .foregroundColor(.secondary)
                    }
                    
                    Spacer()
                    
                    Button(action: copyPromptToClipboard) {
                        HStack(spacing: 5) {
                            Image(systemName: promptCopied ? "checkmark" : "doc.on.doc")
                                .font(.system(size: 11, weight: .semibold))
                            Text(promptCopied ? "Copied!" : "Copy Prompt")
                                .font(.system(size: 11, weight: .medium))
                        }
                        .padding(.horizontal, 10)
                        .padding(.vertical, 6)
                        .background(promptCopied ? Color.green.opacity(0.2) : Color.blue.opacity(0.15))
                        .foregroundColor(promptCopied ? .green : .blue)
                        .clipShape(RoundedRectangle(cornerRadius: 6, style: .continuous))
                    }
                    .buttonStyle(.plain)
                }
                
                Divider()
                
                VStack(alignment: .leading, spacing: 8) {
                    Text("Paste AI Recipe JSON:")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundColor(.secondary)
                    
                    TextEditor(text: $recipeInput)
                        .font(.system(size: 11, design: .monospaced))
                        .frame(height: 70)
                        .padding(6)
                        .background(Color(nsColor: .textBackgroundColor))
                        .clipShape(RoundedRectangle(cornerRadius: 6, style: .continuous))
                        .overlay(
                            RoundedRectangle(cornerRadius: 6, style: .continuous)
                                .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
                        )
                    
                    HStack {
                        Button(action: applyRecipeJSON) {
                            HStack(spacing: 6) {
                                Image(systemName: "plus.circle.fill")
                                Text("Add & Connect Assistant")
                            }
                            .font(.system(size: 12, weight: .medium))
                            .padding(.horizontal, 12)
                            .padding(.vertical, 6)
                            .background(Color.blue)
                            .foregroundColor(.white)
                            .clipShape(RoundedRectangle(cornerRadius: 6, style: .continuous))
                        }
                        .buttonStyle(.plain)
                        .disabled(recipeInput.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                        
                        if let msg = recipeFeedbackMessage {
                            Text(msg)
                                .font(.system(size: 11))
                                .foregroundColor(recipeFeedbackIsError ? .red : .green)
                        }
                        Spacer()
                    }
                }
            }
            .padding(14)
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
        }
    }
    
    // MARK: - Active Custom Connectors
    private var activeCustomConnectorsSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("CUSTOM CONNECTED ASSISTANTS")
                .font(.system(size: 11, weight: .semibold))
                .foregroundColor(.secondary)
                .tracking(0.5)
            
            VStack(spacing: 0) {
                ForEach(connectorManager.customConnectors) { connector in
                    HStack(spacing: 12) {
                        ZStack {
                            RoundedRectangle(cornerRadius: 6, style: .continuous)
                                .fill(Color.purple.opacity(0.15))
                                .frame(width: 28, height: 28)
                            Image(systemName: "person.crop.circle.badge.checkmark")
                                .font(.system(size: 13, weight: .semibold))
                                .foregroundColor(.purple)
                        }
                        
                        VStack(alignment: .leading, spacing: 2) {
                            HStack(spacing: 6) {
                                Text(connector.name)
                                    .font(.system(size: 13, weight: .medium))
                                    .foregroundColor(.primary)
                                Text(connector.format.rawValue.uppercased())
                                    .font(.system(size: 9, weight: .bold))
                                    .padding(.horizontal, 4)
                                    .padding(.vertical, 2)
                                    .background(Color.secondary.opacity(0.2))
                                    .clipShape(RoundedRectangle(cornerRadius: 4, style: .continuous))
                            }
                            Text(connector.path)
                                .font(.system(size: 10, design: .monospaced))
                                .foregroundColor(.secondary)
                                .lineLimit(1)
                                .truncationMode(.middle)
                        }
                        
                        Spacer()
                        
                        Toggle("", isOn: Binding(
                            get: { connector.isEnabled },
                            set: { connectorManager.toggleConnector(id: connector.id, enabled: $0) }
                        ))
                        .toggleStyle(.switch)
                        
                        Button(action: {
                            connectorManager.removeConnector(id: connector.id)
                        }) {
                            Image(systemName: "trash")
                                .font(.system(size: 12))
                                .foregroundColor(.red.opacity(0.8))
                                .padding(4)
                        }
                        .buttonStyle(.plain)
                    }
                    .padding(.horizontal, 14)
                    .padding(.vertical, 10)
                    
                    if connector.id != connectorManager.customConnectors.last?.id {
                        Divider().padding(.horizontal, 14)
                    }
                }
            }
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
        }
    }
    
    // MARK: - Terminal & CLI Harness Section
    private var terminalHarnessSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("TERMINAL & CLI HARNESSES (ONE-LINERS)")
                .font(.system(size: 11, weight: .semibold))
                .foregroundColor(.secondary)
                .tracking(0.5)
            
            VStack(alignment: .leading, spacing: 12) {
                Text("Pipe the output of any command line assistant directly into Agent Speak:")
                    .font(.system(size: 11))
                    .foregroundColor(.secondary)
                
                cliCodeSnippet(label: "Pipe command output to speech", code: "claude \"explain this error\" | agentspeak say")
                cliCodeSnippet(label: "Direct socket stream (Zero file lag)", code: "echo \"say:Build completed\" | nc -U /tmp/agentspeak.sock")
                cliCodeSnippet(label: "Add universal speech function to ~/.zshrc", code: "speak() { \"$@\" | agentspeak say; }")
            }
            .padding(14)
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
        }
    }
    
    // MARK: - Manual Folder / File Watcher
    private var manualWatcherSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("MANUAL CUSTOM WATCHER (POWER USERS)")
                .font(.system(size: 11, weight: .semibold))
                .foregroundColor(.secondary)
                .tracking(0.5)
            
            VStack(alignment: .leading, spacing: 12) {
                HStack(spacing: 10) {
                    TextField("Assistant Name (e.g. My Harness)", text: $manualName)
                        .textFieldStyle(.roundedBorder)
                        .font(.system(size: 11))
                    
                    Picker("Format", selection: $manualFormat) {
                        ForEach(ConnectorFormat.allCases) { fmt in
                            Text(fmt.displayName).tag(fmt)
                        }
                    }
                    .font(.system(size: 11))
                    .frame(width: 170)
                }
                
                HStack(spacing: 8) {
                    TextField("Path to directory or log file", text: $manualPath)
                        .textFieldStyle(.roundedBorder)
                        .font(.system(size: 11))
                    
                    Button("Browse...") {
                        selectPathWithPanel()
                    }
                    .font(.system(size: 11))
                }
                
                HStack {
                    Button(action: addManualWatcher) {
                        HStack(spacing: 6) {
                            Image(systemName: "folder.badge.plus")
                            Text("Add Custom Path")
                        }
                        .font(.system(size: 11, weight: .medium))
                        .padding(.horizontal, 10)
                        .padding(.vertical, 5)
                        .background(Color.secondary.opacity(0.2))
                        .clipShape(RoundedRectangle(cornerRadius: 6, style: .continuous))
                    }
                    .buttonStyle(.plain)
                    .disabled(manualName.isEmpty || manualPath.isEmpty)
                    
                    if let msg = manualFeedbackMessage {
                        Text(msg)
                            .font(.system(size: 11))
                            .foregroundColor(manualFeedbackIsError ? .red : .green)
                    }
                    Spacer()
                }
            }
            .padding(14)
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
        }
    }
    
    // MARK: - Row Helpers
    private func presetConnectorRow(preset: AssistantConnector) -> some View {
        let isDetected = connectorManager.isPathDetected(path: preset.path)
        let iconName: String
        let iconColor: Color
        
        switch preset.id {
        case "preset_cursor":
            iconName = "cursorarrow.rays"
            iconColor = .indigo
        case "preset_cline":
            iconName = "chevron.left.slash.chevron.right"
            iconColor = .blue
        case "preset_roocode":
            iconName = "kangaroo.fill"
            iconColor = .teal
        case "preset_windsurf":
            iconName = "wind"
            iconColor = .cyan
        case "preset_hermes":
            iconName = "flame.fill"
            iconColor = .orange
        case "preset_aider":
            iconName = "pencil.and.outline"
            iconColor = .pink
        default:
            iconName = "person.crop.circle"
            iconColor = .gray
        }
        
        return HStack(spacing: 12) {
            ZStack {
                RoundedRectangle(cornerRadius: 6, style: .continuous)
                    .fill(iconColor.opacity(0.15))
                    .frame(width: 28, height: 28)
                Image(systemName: iconName)
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundColor(iconColor)
            }
            
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(preset.name)
                        .font(.system(size: 13, weight: .medium))
                        .foregroundColor(.primary)
                    
                    HStack(spacing: 3) {
                        Circle()
                            .fill(isDetected ? Color.green : Color.secondary.opacity(0.4))
                            .frame(width: 6, height: 6)
                        Text(isDetected ? "Detected" : "Not Installed")
                            .font(.system(size: 10))
                            .foregroundColor(isDetected ? .green : .secondary)
                    }
                }
                Text(preset.path)
                    .font(.system(size: 10, design: .monospaced))
                    .foregroundColor(.secondary)
                    .lineLimit(1)
                    .truncationMode(.middle)
            }
            Spacer()
            
            Toggle("", isOn: Binding(
                get: { preset.isEnabled },
                set: { connectorManager.toggleConnector(id: preset.id, enabled: $0) }
            ))
            .toggleStyle(.switch)
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 10)
    }
    
    private func workspaceRow(icon: String, color: Color, title: String, subtitle: String, isDetected: Bool, isOn: Binding<Bool>) -> some View {
        HStack(spacing: 12) {
            ZStack {
                RoundedRectangle(cornerRadius: 6, style: .continuous)
                    .fill(color.opacity(0.15))
                    .frame(width: 28, height: 28)
                Image(systemName: icon)
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundColor(color)
            }
            
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(title)
                        .font(.system(size: 13, weight: .medium))
                        .foregroundColor(.primary)
                    
                    HStack(spacing: 3) {
                        Circle()
                            .fill(isDetected ? Color.green : Color.secondary.opacity(0.4))
                            .frame(width: 6, height: 6)
                        Text(isDetected ? "Active" : "Not Installed")
                            .font(.system(size: 10))
                            .foregroundColor(isDetected ? .green : .secondary)
                    }
                }
                Text(subtitle)
                    .font(.system(size: 11))
                    .foregroundColor(.secondary)
            }
            Spacer()
            Toggle("", isOn: isOn)
                .toggleStyle(.switch)
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 10)
    }
    
    private func cliCodeSnippet(label: String, code: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(label)
                .font(.system(size: 10, weight: .semibold))
                .foregroundColor(.secondary)
            HStack {
                Text(code)
                    .font(.system(size: 11, design: .monospaced))
                    .foregroundColor(.primary)
                    .lineLimit(1)
                Spacer()
                Button(action: {
                    let pasteboard = NSPasteboard.general
                    pasteboard.clearContents()
                    pasteboard.setString(code, forType: .string)
                }) {
                    Image(systemName: "doc.on.doc")
                        .font(.system(size: 10))
                        .foregroundColor(.secondary)
                }
                .buttonStyle(.plain)
            }
            .padding(8)
            .background(Color(nsColor: .textBackgroundColor).opacity(0.7))
            .clipShape(RoundedRectangle(cornerRadius: 6, style: .continuous))
        }
    }
    
    // MARK: - Actions
    private func copyPromptToClipboard() {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(UniversalConnectorManager.universalPromptText, forType: .string)
        promptCopied = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.5) {
            self.promptCopied = false
        }
    }
    
    private func applyRecipeJSON() {
        let result = UniversalConnectorManager.shared.parseAndAddRecipe(from: recipeInput)
        switch result {
        case .success(let connector):
            recipeFeedbackMessage = "Successfully connected '\(connector.name)'!"
            recipeFeedbackIsError = false
            recipeInput = ""
            DispatchQueue.main.asyncAfter(deadline: .now() + 4.0) {
                if !self.recipeFeedbackIsError {
                    self.recipeFeedbackMessage = nil
                }
            }
        case .failure(let err):
            recipeFeedbackMessage = err.localizedDescription
            recipeFeedbackIsError = true
        }
    }
    
    private func selectPathWithPanel() {
        let panel = NSOpenPanel()
        panel.canChooseFiles = true
        panel.canChooseDirectories = true
        panel.allowsMultipleSelection = false
        panel.resolvesAliases = true
        
        if panel.runModal() == .OK, let url = panel.url {
            manualPath = url.path
        }
    }
    
    private func addManualWatcher() {
        let validation = SecurityPathValidator.validate(path: manualPath)
        guard validation.isValid else {
            manualFeedbackMessage = validation.errorMessage ?? "Invalid path"
            manualFeedbackIsError = true
            return
        }
        
        let connector = AssistantConnector(
            name: manualName,
            path: validation.sanitizedPath,
            format: manualFormat,
            isPreset: false,
            isEnabled: true
        )
        
        connectorManager.customConnectors.append(connector)
        connectorManager.saveConnectors()
        
        manualFeedbackMessage = "Added '\(manualName)' successfully!"
        manualFeedbackIsError = false
        manualName = ""
        manualPath = ""
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 4.0) {
            if !self.manualFeedbackIsError {
                self.manualFeedbackMessage = nil
            }
        }
    }
    
    private func checkPath(_ rawPath: String) -> Bool {
        let validation = SecurityPathValidator.validate(path: rawPath)
        guard validation.isValid else { return false }
        return FileManager.default.fileExists(atPath: validation.sanitizedPath)
    }
}
