import SwiftUI

// MARK: - Apple HIG Connected AI Assistants View
public struct DashboardWorkspacesView: View {
    @Binding var watchAntigravity: Bool
    @Binding var watchClaude: Bool
    @Binding var watchOpenCode: Bool
    @Binding var watchTerminal: Bool
    
    public init(
        watchAntigravity: Binding<Bool>,
        watchClaude: Binding<Bool>,
        watchOpenCode: Binding<Bool>,
        watchTerminal: Binding<Bool>
    ) {
        self._watchAntigravity = watchAntigravity
        self._watchClaude = watchClaude
        self._watchOpenCode = watchOpenCode
        self._watchTerminal = watchTerminal
    }
    
    public var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Privacy Reassurance Card
            HStack(spacing: 12) {
                ZStack {
                    RoundedRectangle(cornerRadius: 6, style: .continuous)
                        .fill(Color.green.opacity(0.15))
                        .frame(width: 28, height: 28)
                    Image(systemName: "lock.shield.fill")
                        .font(.system(size: 14, weight: .semibold))
                        .foregroundColor(.green)
                }
                
                VStack(alignment: .leading, spacing: 2) {
                    Text("100% Private • Zero Microphone Access")
                        .font(.system(size: 12, weight: .semibold))
                        .foregroundColor(.primary)
                    Text("Agent Speak only vocalizes text generated by your AI tools. It never uses, records, or monitors your microphone.")
                        .font(.system(size: 11))
                        .foregroundColor(.secondary)
                }
                Spacer()
            }
            .padding(12)
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
            
            Text("CONNECTED AI CODING ASSISTANTS")
                .font(.system(size: 11, weight: .semibold))
                .foregroundColor(.secondary)
                .tracking(0.5)
            
            VStack(spacing: 0) {
                workspaceRow(
                    icon: "circle.hexagongrid.circle.fill",
                    color: .purple,
                    title: "Antigravity Assistant",
                    subtitle: "Speaks conversational responses from Antigravity IDE and CLI",
                    isOn: $watchAntigravity
                )
                Divider().padding(.horizontal, 14)
                
                workspaceRow(
                    icon: "terminal.fill",
                    color: .orange,
                    title: "Claude Code",
                    subtitle: "Speaks session answers and output from Claude Code CLI",
                    isOn: $watchClaude
                )
                Divider().padding(.horizontal, 14)
                
                workspaceRow(
                    icon: "chevron.left.forwardslash.chevron.right",
                    color: .cyan,
                    title: "OpenCode & Other Agents",
                    subtitle: "Speaks activity logs and answers from supported developer agents",
                    isOn: $watchOpenCode
                )
                Divider().padding(.horizontal, 14)
                
                workspaceRow(
                    icon: "apple.terminal.on.rectangle.fill",
                    color: .green,
                    title: "Terminal & UNIX Socket",
                    subtitle: "Accepts speech commands from custom scripts, shortcuts, and CLI",
                    isOn: $watchTerminal
                )
            }
            .background(Color(nsColor: .controlBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(Color(nsColor: .separatorColor), lineWidth: 0.5)
            )
            
            HStack(spacing: 8) {
                Image(systemName: "bolt.fill")
                    .foregroundColor(.yellow)
                Text("Instant Streaming: Automatically begins speaking sentences in real-time as your AI responds.")
                    .font(.system(size: 11))
                    .foregroundColor(.secondary)
            }
            .padding(.top, 4)
        }
    }
    
    private func workspaceRow(icon: String, color: Color, title: String, subtitle: String, isOn: Binding<Bool>) -> some View {
        HStack(spacing: 12) {
            ZStack {
                RoundedRectangle(cornerRadius: 6, style: .continuous)
                    .fill(color.opacity(0.15))
                    .frame(width: 28, height: 28)
                Image(systemName: icon)
                    .font(.system(size: 13, weight: .semibold))
                    .foregroundColor(color)
            }
            
            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.system(size: 13, weight: .medium))
                    .foregroundColor(.primary)
                Text(subtitle)
                    .font(.system(size: 11))
                    .foregroundColor(.secondary)
            }
            Spacer()
            Toggle("", isOn: isOn)
                .toggleStyle(.switch)
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 10)
    }
}
